import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from '@/app/ui/fonts';
import PageHeader from "./components/header";
import PageFooter from "./components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <PageHeader />
        <main className="flex min-h-screen flex-col">
          {children}
        </main>
        <PageFooter />
      </body>
    </html>
  );
}
